import type { Connector } from './connectors/types.js'
import { fail } from './exec.js'
import { PLATFORM_NETWORK } from './network.js'
import { readToggles } from './posture.js'
import { CLAUDE_HOME, CLAUDE_VOLUME } from './session-files.js'
import { shellQuote } from './shell.js'
import { readEnv } from './target-env.js'
import { onHarnessImage } from './verify.js'

/**
 * Memory: one claude-mem worker service on the Target, shared by every
 * Session, brought up with the `sessions` toggle (ADR 0010, resolving ADR
 * 0007's deferral). Its own compose project in the install directory, on the
 * platform network so a Session — through the loopback forwarder of #93 —
 * and, later, the Access service reach it by service name:
 *
 *   <installDir>/memory/compose.yaml   the service, generated here
 *
 * The platform owns the runtime and nothing else: the container mounts the
 * same shared `~/.claude` volume the Sessions use and runs the installed
 * plugin's own worker script out of it, so plugin and worker cannot drift
 * and a plugin update done in a Session is a worker restart. The worker
 * summarises with the `claude` CLI, unattended, so it gets the Run token like
 * a Run does — under the name Claude Code reads, which a Session never
 * carries. Runs do not write to Memory; a Run's memory is its Run Log (ADR
 * 0009).
 *
 * Pure apart from `memoryUp` and `memoryDown`, which need only a Connector,
 * so the install can bring the service up on an upgrade and the `sessions`
 * hook can bring it up and down without a prompter.
 */

export const MEMORY_PROJECT = 'sandcastle-vps-memory'
export const MEMORY_SERVICE = 'memory'
/** The port the plugin's worker serves on, and the one its hooks dial on
 *  loopback; the forwarder of #93 maps one to the other. */
export const MEMORY_PORT = 37777

/** Where the worker keeps its store inside the container: the plugin's own
 *  default beside `~/.claude` — CLAUDE_HOME's parent, spelled out because
 *  that constant arrives through an import cycle and is not there yet when
 *  this module loads; a test holds the two together. A store made under
 *  claude-tmux has the same layout and can be mounted here as it is. */
export const MEMORY_DATA_MOUNT = '/home/agent/.claude-mem'

/** The named volume the store lives in on a fresh Target. External, like the
 *  login volume: created by enabling `sessions`, owned by no compose project,
 *  so `down` never touches it. */
export const MEMORY_VOLUME = 'sandcastle-vps-memory'

/** The Local Config key naming a directory on the Target to use as the store
 *  instead of the volume — the live VPS's existing claude-mem store at
 *  cutover (#95). Empty means the volume. */
export const DATA_DIR_KEY = 'MEMORY_DATA_DIR'

export const memoryDir = (installDir: string): string => `${installDir}/memory`

/**
 * The store's location, from the Target's Local Config: an absolute path to
 * bind-mount as is, or `undefined` for the named volume. A relative path is
 * refused rather than resolved — compose would resolve it against the
 * generated file, which is not what an operator typing `~/.claude-mem` meant.
 */
export const memoryDataDir = (envContent: string): string | undefined => {
  const dir = readEnv(envContent, DATA_DIR_KEY)
  if (dir === undefined) return undefined
  if (!dir.startsWith('/')) {
    throw new Error(
      `${DATA_DIR_KEY} must be an absolute path on the Target, not "${dir}". ` +
        'Leave it empty for the named volume.',
    )
  }
  return dir
}

/** A YAML scalar that survives any path the operator chose: a JSON string is
 *  a YAML string. */
const yaml = (value: string): string => JSON.stringify(value)

/**
 * The Memory service's compose file. Generated rather than shipped so the
 * mounts can be absolute and the store can be either a volume or the
 * operator's directory; regenerated on every up, since it holds no state.
 *
 * No port is published: the worker is reached over the platform network by
 * name, and the loopback forwarder (#93) and the Origin-rewriting proxy (#94)
 * are the two things that ever get to it. Every `CLAUDE_MEM_*` variable here
 * overrides the plugin's settings file, which is how a store carried over
 * from another machine — whose settings name that machine's paths — works
 * here unchanged.
 */
export const memoryCompose = (installDir: string, dataDir?: string): string => {
  const store = dataDir
    ? `      # The operator's own store, used as is (${DATA_DIR_KEY}).
      - ${yaml(`${dataDir}:${MEMORY_DATA_MOUNT}`)}`
    : `      # The store, in a named volume that outlives this compose project.
      - ${MEMORY_VOLUME}:${MEMORY_DATA_MOUNT}`
  const storeVolume = dataDir
    ? ''
    : `  ${MEMORY_VOLUME}:
    external: true
`
  return `# The Memory service (ADR 0010): the claude-mem worker every Session on this
# Target shares. Generated by the creator CLI when sessions is enabled or the
# Target is upgraded; do not edit, it is written over.
name: ${MEMORY_PROJECT}

services:
  ${MEMORY_SERVICE}:
    build:
      context: ${yaml(`${installDir}/docker/memory`)}
      args:
        # The same account the Sessions run as, so the shared volume and a
        # store the operator points at are writable. Filled from the Target's
        # environment file at \`up\`.
        OPERATOR_UID: \${OPERATOR_UID:?read off the Target by the install}
        OPERATOR_GID: \${OPERATOR_GID:?read off the Target by the install}
    hostname: ${MEMORY_SERVICE}
    environment:
      # Bind every interface in the container's own namespace: the worker is
      # dialled by service name over the platform network, and its admin
      # routes still refuse anything that is not its own loopback.
      CLAUDE_MEM_WORKER_HOST: 0.0.0.0
      CLAUDE_MEM_WORKER_PORT: ${yaml(String(MEMORY_PORT))}
      CLAUDE_MEM_DATA_DIR: ${MEMORY_DATA_MOUNT}
      # The plugin lives in the shared login volume, where Claude Code in a
      # Session installed it.
      CLAUDE_CONFIG_DIR: ${CLAUDE_HOME}
      # The Run token, as a Run has it: the worker summarises unattended, and
      # an OAuth flow has nowhere to happen (ADR 0010). Filled at \`up\`, never
      # written here.
      CLAUDE_CODE_OAUTH_TOKEN: \${CLAUDE_CODE_OAUTH_TOKEN:-}
    volumes:
      # The plugin, out of the same volume every Session mounts.
      - ${CLAUDE_VOLUME}:${CLAUDE_HOME}
${store}
      # uv's cache: Chroma is fetched into it on first start, and a restart
      # should not fetch it again.
      - memory_cache:/home/agent/.cache
    restart: unless-stopped

volumes:
  ${CLAUDE_VOLUME}:
    external: true
${storeVolume}  memory_cache:

networks:
  # The platform network, so a Session's forwarder and the Access service
  # resolve this by name.
  default:
    name: ${PLATFORM_NETWORK}
    external: true
`
}

// ------------------------------------------------------------------- scripts

/** The Memory compose project, with the Target's environment file for
 *  interpolation — that is where the uid and the token come from. */
export const memoryComposeScript = (installDir: string, args: string): string =>
  `cd ${shellQuote(memoryDir(installDir))} && ` +
  `docker compose --env-file ${shellQuote(`${installDir}/.env`)} ${args}`

/** Write the compose file from stdin, beside the target and moved into place,
 *  like every other file this CLI puts on a Target. */
export const writeMemoryFileScript = (installDir: string, file: string): string => {
  const dir = shellQuote(memoryDir(installDir))
  const target = shellQuote(`${memoryDir(installDir)}/${file}`)
  return `set -eu
mkdir -p ${dir}
tmp="$(mktemp ${dir}/.${file}.XXXXXX)"
cat > "$tmp"
mv "$tmp" ${target}`
}

/** Create the store volume unless it is there. Inspect first, so "already
 *  exists" is not mistaken for the daemon not answering. */
export const ensureMemoryVolumeScript = (): string =>
  `docker volume inspect ${MEMORY_VOLUME} > /dev/null 2>&1 || docker volume create ${MEMORY_VOLUME} > /dev/null`

/** The running service's state, one line, or nothing when it is not up. */
export const memoryStateScript = (installDir: string): string =>
  `${memoryComposeScript(installDir, "ps --format '{{.Service}}\\t{{.State}}'")} 2> /dev/null || true`

/**
 * Ask the worker for its health the way a Session will: over the platform
 * network, by service name. Through a throwaway container on the Harness
 * image — on the Target by definition, and it has curl — rather than from
 * the Target's own shell, which is not on that network. Read-only.
 */
export const memoryHealthScript = (installDir: string): string =>
  `${onHarnessImage(
    installDir,
    PLATFORM_NETWORK,
    `curl -sS -m 5 http://${MEMORY_SERVICE}:${MEMORY_PORT}/api/health`,
  )} 2> /dev/null || true`

export interface MemoryHealth {
  readonly ok: boolean
  /** The plugin version the worker reports, which is the version it runs. */
  readonly version?: string
}

export const parseHealth = (stdout: string): MemoryHealth => {
  try {
    const answer: unknown = JSON.parse(stdout.trim())
    if (typeof answer !== 'object' || answer === null) return { ok: false }
    const { status, version } = answer as { status?: unknown; version?: unknown }
    return {
      ok: status === 'ok',
      version: typeof version === 'string' && version ? version : undefined,
    }
  } catch {
    return { ok: false }
  }
}

/**
 * Bring the Memory service up, or up to date: write the compose file, make
 * sure the store exists, then build and start it. Idempotent, and asks
 * nothing — the install runs this on an upgrade of a Target with sessions on.
 */
export const memoryUp = async (
  connector: Connector,
  installDir: string,
  envContent: string,
  log: (line: string) => void,
): Promise<void> => {
  const dataDir = memoryDataDir(envContent)
  const written = await connector.exec(writeMemoryFileScript(installDir, 'compose.yaml'), {
    stdin: memoryCompose(installDir, dataDir),
  })
  if (written.code !== 0) throw fail('Writing memory/compose.yaml', written.code, written.stderr)
  if (!dataDir) {
    const volume = await connector.exec(ensureMemoryVolumeScript())
    if (volume.code !== 0) {
      throw fail(`Creating the ${MEMORY_VOLUME} volume`, volume.code, volume.stderr)
    }
  }
  log(
    `\nBuilding the Memory image and starting the claude-mem worker, store ${
      dataDir ? `at ${dataDir}` : `in the ${MEMORY_VOLUME} volume`
    }…`,
  )
  const up = await connector.exec(memoryComposeScript(installDir, 'up -d --build'))
  if (up.code !== 0) throw fail('docker compose up (memory)', up.code, up.stderr)
}

/** `down` without `-v`: the store is external or the operator's, and the
 *  cache is only a cache. Nothing to do on a Target where the service was
 *  never brought up. */
export const memoryDownScript = (installDir: string): string => `set -eu
cd ${shellQuote(memoryDir(installDir))} 2> /dev/null || exit 0
[ -f compose.yaml ] || exit 0
docker compose --env-file ${shellQuote(`${installDir}/.env`)} down`

export const memoryDown = async (connector: Connector, installDir: string): Promise<void> => {
  const down = await connector.exec(memoryDownScript(installDir))
  if (down.code !== 0) throw fail('docker compose down (memory)', down.code, down.stderr)
}

// -------------------------------------------------------------------- status

export interface MemoryStatus {
  /** The `sessions` toggle: Memory travels with it (ADR 0010). */
  readonly enabled: boolean
  /** What `docker compose ps` said about the service; empty when not up. */
  readonly service: string
  /** What the worker answered over the platform network. */
  readonly health: MemoryHealth
  /** Where the store is: the operator's directory, or the volume. */
  readonly dataDir?: string
}

export const MEMORY_OFF: MemoryStatus = { enabled: false, service: '', health: { ok: false } }

/**
 * Read-only, like everything `status` does. The health probe only runs when
 * the service reports itself running: a throwaway container against a worker
 * that is not there would just wait out its timeout.
 */
export const gatherMemory = async (
  connector: Connector,
  installDir: string,
  envContent: string,
): Promise<MemoryStatus> => {
  const enabled = readToggles(envContent).sessions
  // Reported as written even when it is not usable: `status` says what is
  // there, and the up is where a bad value is refused.
  const dataDir = readEnv(envContent, DATA_DIR_KEY)
  const state = await connector.exec(memoryStateScript(installDir))
  const service = state.stdout.trim()
  const health =
    enabled && /\brunning\b/u.test(service)
      ? parseHealth((await connector.exec(memoryHealthScript(installDir))).stdout)
      : { ok: false }
  return { enabled, service, health, dataDir }
}

/** The Memory section of the status report. */
export const formatMemory = (status: MemoryStatus): string[] => {
  const store = status.dataDir
    ? `  store       ${status.dataDir}, the operator's own directory`
    : `  store       the ${MEMORY_VOLUME} volume`
  if (!status.enabled) {
    const stale = status.service
      ? ' — but its service is still up; disable and enable sessions'
      : ''
    return [`  off — comes up with sessions${stale}`]
  }
  if (!/\brunning\b/u.test(status.service)) {
    return [
      '  on          but the service is not running — disable and enable sessions to start it',
      store,
    ]
  }
  if (!status.health.ok) {
    return [
      `  on          the service is up but the worker is not answering on ${MEMORY_SERVICE}:${MEMORY_PORT} —`,
      '              usually claude-mem is not installed in the shared volume yet: inside any',
      '              Session, run `claude plugin install claude-mem@thedotmack`. Its log says.',
      store,
    ]
  }
  return [
    `  on          claude-mem ${status.health.version ?? '(version unknown)'} answering on ${MEMORY_SERVICE}:${MEMORY_PORT} over the platform network`,
    store,
  ]
}
