import type { Connector } from './connectors/types.js'
import { fail } from './install.js'
import { PLATFORM_NETWORK } from './network.js'
import type { TargetProfile } from './profiles.js'
import { shellQuote } from './shell.js'
import { readEnv } from './target-env.js'

/**
 * What a Session is made of, on the Target: one long-lived container per
 * Project, built from that Project's own image, whose tmux server is what the
 * operator attaches to (ADR 0007).
 *
 * Each Session is its own compose project, so the stack's
 * `up --remove-orphans` can never reach it, and it joins the platform network
 * by name so it resolves the Harness and, later, the Memory. The container's
 * main process is the image's own `sleep infinity`; tmux runs inside it and
 * outlives any attach, which is the whole point — a dropped connection loses
 * nothing.
 *
 * What a Session does *not* get in this slice: credentials, the operator's
 * login, persisted state. Those are #88 and #89. In particular nothing here
 * injects `CLAUDE_CODE_OAUTH_TOKEN` — a session container must not carry it
 * (ADR 0010), and a test holds that.
 *
 * Pure, plus the one write both callers share: Onboarding generates these
 * files and the Sessions menu (sessions.ts) regenerates them, and `status`
 * lists what is running. None of the three should import the menu.
 */

/** The label every session container carries, and the only way `status`
 *  finds them: the engine, not the stack's compose project. */
export const SESSION_LABEL = 'sandcastle-vps.session'

/** The tmux session inside the container. One per Session; `new-session -A`
 *  attaches to it when it exists and creates it when it does not. */
const TMUX_SESSION = 'main'

/** Compose project and container name, both. Distinct from the stack's
 *  project by construction, which is what keeps `--remove-orphans` away. */
export const sessionProject = (name: string): string => `sandcastle-session-${name}`

/** Where the Session's compose file lives, under the install directory. */
export const sessionDir = (installDir: string, name: string): string =>
  `${installDir}/sessions/${name}`

export interface SessionSpec {
  readonly name: string
  readonly imageName: string
  readonly installDir: string
  readonly workspaceRoot: string
  /** The Target's docker group, so the mounted socket is usable by the
   *  unprivileged agent user the image runs as. */
  readonly dockerGid: string
}

/** What the Target's environment file settles about every Session on it. */
export const specFor = (
  profile: TargetProfile,
  envContent: string,
  project: { readonly name: string; readonly imageName: string },
): SessionSpec => ({
  name: project.name,
  imageName: project.imageName,
  installDir: profile.installDir,
  workspaceRoot: readEnv(envContent, 'WORKSPACE_ROOT') ?? profile.workspaceRoot,
  dockerGid: readEnv(envContent, 'DOCKER_GID') ?? '',
})

/** YAML-safe: a JSON string is a YAML string, and paths and names come from
 *  the operator. */
const quoted = (value: string): string => JSON.stringify(value)

/**
 * The Session's compose file. Regenerated on every start — it is derived from
 * the Target's environment and owns no state, so there is nothing in it to
 * preserve, and regenerating is how a changed docker group or workspace root
 * takes effect.
 */
export const sessionCompose = ({
  name,
  imageName,
  workspaceRoot,
  dockerGid,
}: SessionSpec): string => `# The Session on ${name}: one container from the Project's own image, in its
# own compose project (ADR 0007). Generated by sandcastle-vps on every Session
# start — edit the Project's .sandcastle/Dockerfile, not this.
name: ${quoted(sessionProject(name))}

services:
  session:
    image: ${quoted(imageName)}
    container_name: ${quoted(sessionProject(name))}
    hostname: ${quoted(name)}
    labels:
      ${SESSION_LABEL}: ${quoted(name)}
    # tmux's server is reparented to PID 1 when an attach ends; the image's
    # own \`sleep infinity\` does not reap, so an init does.
    init: true
    working_dir: ${quoted(`${workspaceRoot}/${name}`)}
    environment:
      # The Session shell is bash (ADR 0010); tmux reads this for new windows.
      SHELL: /bin/bash
    # The Target's docker group, so the socket below is usable by the agent
    # user. This is the exposure ADR 0007 gates behind the sessions toggle.
    group_add:
      - ${quoted(dockerGid)}
    volumes:
      # Path parity, as in the Harness: a Sandbox started from here bind-mounts
      # worktrees by the path the Target's daemon resolves.
      - ${quoted(`${workspaceRoot}:${workspaceRoot}`)}
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  # The platform network, created by the install; joined by name so the
  # Harness and the Memory resolve from inside (ADR 0010).
  default:
    name: ${PLATFORM_NETWORK}
    external: true
`

/**
 * The Dev Containers file, so an editor attaches to the same container. The
 * only thing written into the repository, because the spec requires that
 * path (ADR 0007) — and gitignored from inside its own directory, so the
 * Project's tracked .gitignore is left alone and the directory never shows
 * up for an agent to commit.
 */
export const devcontainer = ({ name, installDir, workspaceRoot }: SessionSpec): string =>
  `${JSON.stringify(
    {
      name,
      dockerComposeFile: [`${sessionDir(installDir, name)}/compose.yaml`],
      service: 'session',
      workspaceFolder: `${workspaceRoot}/${name}`,
      // The Session outlives the editor, as it outlives an ssh connection.
      shutdownAction: 'none',
    },
    null,
    2,
  )}\n`

/** Write the compose file; the content arrives on stdin, as the environment
 *  file's does, so there is one way a file reaches the Target. */
export const writeComposeScript = (installDir: string, name: string): string => {
  const dir = shellQuote(sessionDir(installDir, name))
  return `set -eu
mkdir -p ${dir}
cat > ${dir}/compose.yaml`
}

/** Seed the devcontainer file: written only when absent, since an operator
 *  may have tuned it, and self-ignored so git never sees the directory. */
export const writeDevcontainerScript = (workspaceRoot: string, name: string): string => {
  const dir = shellQuote(`${workspaceRoot}/${name}/.devcontainer`)
  return `set -eu
mkdir -p ${dir}
printf '*\\n' > ${dir}/.gitignore
if [ -e ${dir}/devcontainer.json ]; then
  cat > /dev/null
else
  cat > ${dir}/devcontainer.json
fi`
}

/** Both generated artifacts, on the Target. Onboarding calls this, and so
 *  does every Session start — which is how a Project Onboarded before
 *  Sessions existed gets them without a step of its own. */
export const writeSessionArtifacts = async (
  connector: Connector,
  spec: SessionSpec,
): Promise<void> => {
  if (!spec.dockerGid) {
    throw new Error(
      'The Target’s environment file has no DOCKER_GID, so a Session could not use the ' +
        'Docker socket. Run install/upgrade first.',
    )
  }
  const compose = await connector.exec(writeComposeScript(spec.installDir, spec.name), {
    stdin: sessionCompose(spec),
  })
  if (compose.code !== 0) {
    throw fail('Writing the Session compose file', compose.code, compose.stderr)
  }
  const dev = await connector.exec(writeDevcontainerScript(spec.workspaceRoot, spec.name), {
    stdin: devcontainer(spec),
  })
  if (dev.code !== 0) throw fail('Writing the devcontainer file', dev.code, dev.stderr)
}

/**
 * Start the Session, or find it already started. `up -d` is idempotent on a
 * running project, which is what makes a second open attach to the same
 * container; the image check in front of it turns compose's attempt to pull
 * a nonexistent image into a sentence.
 */
export const startScript = (installDir: string, name: string, imageName: string): string => {
  const dir = shellQuote(sessionDir(installDir, name))
  return `set -eu
if ! docker image inspect ${shellQuote(imageName)} > /dev/null 2>&1; then
  printf 'error\\tThe image %s is not built. A Run builds it, or retry the build from "Add a Project".\\n' ${shellQuote(imageName)}
  exit 0
fi
if [ -n "$(docker ps -q --filter ${shellQuote(`label=${SESSION_LABEL}=${name}`)})" ]; then
  printf 'state\\trunning\\n'
  exit 0
fi
cd ${dir} && docker compose up -d > /dev/null 2>&1
printf 'state\\tstarted\\n'`
}

/**
 * What runs on the Target's terminal to land in the Session: exec into the
 * container with a TTY, and attach to its tmux session or create it. TERM is
 * the operator's, carried by ssh, so colours and keys inside match the
 * terminal outside.
 */
export const attachScript = (name: string): string =>
  `exec docker exec -it -e "TERM=\${TERM:-xterm}" ${shellQuote(sessionProject(name))} ` +
  `tmux new-session -A -s ${TMUX_SESSION}`

/** Explicit, and the only way a Session ends: the container and its tmux
 *  server go together. A detach is not this. */
export const stopScript = (installDir: string, name: string): string =>
  `cd ${shellQuote(sessionDir(installDir, name))} && docker compose down > /dev/null 2>&1`

/** Every running Session on the Target, from the engine. `status` and the
 *  menu both use it; neither goes through the stack's compose project. */
export const listScript = (): string =>
  `docker ps --filter label=${SESSION_LABEL} --format '{{.Label "${SESSION_LABEL}"}}\t{{.Status}}'`

export interface RunningSession {
  readonly project: string
  /** As the engine reports it — "Up 2 hours". */
  readonly status: string
}

export const parseSessions = (stdout: string): RunningSession[] =>
  stdout
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .flatMap((line) => {
      const [project, ...status] = line.split('\t')
      return project ? [{ project, status: status.join(' ').trim() }] : []
    })
