import { APP_ID } from '../app-id.js'
import type { Connector } from './connectors/types.js'
import { exposedListeners, parseListeners, stackPorts, type Listener } from './listeners.js'
import { shellQuote } from './shell.js'

/**
 * What the install asserts once the stack is up.
 *
 * The retired deploy checked itself from the inside, which meant a Target that
 * never finished starting reported nothing at all. The CLI checks from outside
 * instead: it can say "the Harness is not answering" where the Harness could
 * only fail to say it.
 *
 * Two of the three checks need an HTTP client, and the Target is not required
 * to have one — preflight asks for Docker and nothing else. They borrow the
 * Harness image, which was just built on the Target and ships curl, and run it
 * in the Target's own network namespace. That is what makes them outside
 * checks: they reach the published loopback ports an operator would reach, so
 * a `ports:` mapping that never took effect fails them.
 */

export interface Check {
  readonly ok: boolean
  readonly label: string
  readonly detail: string
}

/** One label, so the placeholder `verifyInstall` starts from cannot drift
 *  from the one `syncCheck` returns. Capitalised as CONTEXT.md capitalises
 *  them: these are operator-facing prose, not ids like preflight's. */
const SYNC_LABEL = 'Harness synced'

/** `apps` is the Orchestrator's own view of what has synced with it. */
const APPS_QUERY = '{ apps { name url connected functionCount error } }'

interface OrchestratorApp {
  readonly name?: string
  readonly url?: string
  readonly connected?: boolean
  readonly functionCount?: number
  readonly error?: string | null
}

/**
 * Run a command on the Target's own loopback, using the image the install just
 * built there.
 *
 * `--network host` is the point: a probe run inside the Harness container would
 * reach that container's loopback, which is not the Target's, so a published
 * port that never took effect would still pass. Borrowing the Harness image
 * rather than pulling one keeps the Target's dependencies at Docker alone — and
 * it is on the Target by definition, because the install just built it.
 */
export const onTargetLoopback = (installDir: string, command: string): string =>
  `cd ${shellQuote(installDir)} && ` +
  `docker run --rm --network host "$(docker compose images -q harness | head -1)" ${command}`

export const appsQueryScript = (installDir: string): string =>
  onTargetLoopback(
    installDir,
    `curl -sS -m 10 -X POST http://127.0.0.1:8288/v0/gql -H 'content-type: application/json' ` +
      `-d ${shellQuote(JSON.stringify({ query: APPS_QUERY }))}`,
  )

/**
 * A Dispatch the Orchestrator must refuse, sent to the surface an operator on
 * the Target would use. The Project name is generated by the caller so it
 * cannot collide with a real checkout.
 */
export const dispatchProbeScript = (installDir: string, port: number, project: string): string =>
  onTargetLoopback(
    installDir,
    `curl -sS -m 10 -w '\\n%{http_code}' -X POST http://127.0.0.1:${port}/dispatch ` +
      `-H 'content-type: application/json' ` +
      `-d ${shellQuote(JSON.stringify({ project, task: 'install verification — never dispatched' }))}`,
  )

/** Both tables at once, with a marker the parser splits on. */
export const LISTENERS_SCRIPT = `cat /proc/net/tcp 2>/dev/null || true
printf '=====\\n'
cat /proc/net/tcp6 2>/dev/null || true`

export const parseBothTables = (stdout: string): Listener[] => {
  const [tcp = '', tcp6 = ''] = stdout.split('=====\n')
  return [...parseListeners(tcp), ...parseListeners(tcp6)]
}

export const syncCheck = (stdout: string): Check => {
  const label = SYNC_LABEL
  let apps: OrchestratorApp[]
  try {
    apps = JSON.parse(stdout)?.data?.apps ?? []
  } catch {
    // Anything that is not JSON came from docker or curl, not the
    // Orchestrator, and its first line is the useful half.
    return { ok: false, label, detail: stdout.trim().split('\n')[0] ?? 'no answer' }
  }
  const app = apps.find((candidate) => candidate.name === APP_ID)
  if (!app) {
    return {
      ok: false,
      label,
      detail: apps.length === 0 ? 'the Orchestrator has synced no app' : 'no app called ' + APP_ID,
    }
  }
  if (app.error) return { ok: false, label, detail: `${APP_ID}: ${app.error}` }
  if (!app.functionCount) {
    return { ok: false, label, detail: `${APP_ID} synced, but with no functions` }
  }
  return {
    ok: true,
    label,
    detail: `${APP_ID}, ${app.functionCount} function${app.functionCount === 1 ? '' : 's'}`,
  }
}

export const exposureCheck = (listeners: readonly Listener[], harnessPort: number): Check => {
  const label = 'loopback only'
  const exposed = exposedListeners(listeners, stackPorts(harnessPort))
  if (exposed.length > 0) {
    return {
      ok: false,
      label,
      detail: `reachable off the Target: ${exposed.map((l) => `${l.address}:${l.port}`).join(', ')} — nothing behind them authenticates`,
    }
  }
  // A published port that is not listening at all is not a pass: it means the
  // stack is not up, and the Dispatch check below would be the one to say so.
  const published = listeners.filter((listener) => listener.port === harnessPort)
  if (published.length === 0) {
    return { ok: false, label, detail: `nothing is listening on ${harnessPort}` }
  }
  return { ok: true, label, detail: `${harnessPort} and 8288 are on loopback, and nothing else is` }
}

export const dispatchCheck = (stdout: string): Check => {
  const label = 'Dispatch refuses'
  const lines = stdout.trim().split('\n')
  const status = lines.at(-1)?.trim()
  const body = lines.slice(0, -1).join('\n')
  if (status !== '400') {
    return {
      ok: false,
      label,
      detail: `a Dispatch to a Project that does not exist answered ${status || 'nothing'}${body ? `: ${body}` : ''}`,
    }
  }
  return { ok: true, label, detail: '400 for a Project that does not exist' }
}

export interface VerifyOptions {
  readonly installDir: string
  readonly harnessPort: number
  /** How many times to ask whether the Harness has synced. The Orchestrator
   *  syncs on its own schedule, so the first answer is routinely "not yet". */
  readonly attempts?: number
  readonly sleep?: (ms: number) => Promise<void>
  readonly delayMs?: number
  /** A Project name that cannot exist. Injected so the check is repeatable. */
  readonly absentProject?: string
}

const wait = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms))

/**
 * The three things that must be true of a Target once the stack is up. Run in
 * this order because it is the order they fail in: an unsynced Harness
 * explains a refused Dispatch, and neither says anything useful about ports.
 */
export const verifyInstall = async (
  connector: Connector,
  {
    installDir,
    harnessPort,
    attempts = 30,
    delayMs = 3000,
    sleep = wait,
    absentProject = `no-such-project-${Math.random().toString(36).slice(2, 10)}`,
  }: VerifyOptions,
): Promise<Check[]> => {
  let sync: Check = { ok: false, label: SYNC_LABEL, detail: 'never asked' }
  for (let attempt = 0; attempt < attempts; attempt++) {
    if (attempt > 0) await sleep(delayMs)
    const { stdout, stderr } = await connector.exec(appsQueryScript(installDir))
    sync = syncCheck(stdout.trim() || stderr.trim())
    if (sync.ok) break
  }

  const listeners = await connector.exec(LISTENERS_SCRIPT)
  const exposure = exposureCheck(parseBothTables(listeners.stdout), harnessPort)

  const dispatch = await connector.exec(dispatchProbeScript(installDir, harnessPort, absentProject))
  return [sync, exposure, dispatchCheck(dispatch.stdout.trim() || dispatch.stderr.trim())]
}

export const formatChecks = (checks: readonly Check[]): string =>
  checks
    // 18, because `Dispatch refuses` is 16 and a column with no gap after it
    // reads as one word: "Dispatch refuses400 for a Project…".
    .map((check) => `  ${check.ok ? 'ok  ' : 'FAIL'}  ${check.label.padEnd(18)}${check.detail}`)
    .join('\n')
