#!/usr/bin/env bash
#
# Cut the live VPS over from claude-tmux to sandcastle-vps (issue #95).
#
# A wizard: it walks the operator through the attended steps one stage at a
# time, runs over ssh the checks that can be run from the dev machine, and
# ends with the record of everything done by hand, for the issue comment.
# Run it ONCE, from the dev machine — never from inside a claude-tmux
# container, which stage 7 deletes. Generated by the /wizard skill; the
# README's Access section says when to run it.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it (shfmt may reformat it). Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput > /dev/null 2>&1 && [[ "$(tput colors 2> /dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold)
  DIM=$(tput dim)
  RESET=$(tput sgr0)
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  RED=$(tput setaf 1)
else
  BOLD=""
  DIM=""
  RESET=""
  BLUE=""
  GREEN=""
  YELLOW=""
  RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput > /dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say() { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  {
    if command -v wslview > /dev/null 2>&1; then
      wslview "$url"
    elif command -v explorer.exe > /dev/null 2>&1; then
      explorer.exe "$url"
    elif command -v xdg-open > /dev/null 2>&1; then
      xdg-open "$url"
    elif command -v open > /dev/null 2>&1; then
      open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } > /dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh > /dev/null 2>&1 && gh auth status > /dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" > /dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh > /dev/null 2>&1 && gh auth status > /dev/null 2>&1; then
    if gh variable set "$name" --body "$value" > /dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  ((${#WRITTEN_ENV[@]})) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if ((${#SKIPPED[@]})); then
    printf '\n'
    warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: one stage() per step of #95, in its order, plus the record at the end.
# ──────────────────────────────────────────────────────────────────────────

# Re-runs remember the answers here; none of them is a secret. Not the repo's
# own .env, which describes a different machine.
ENV_FILE="${ENV_FILE:-$HOME/.config/sandcastle-vps/cutover.env}"
mkdir -p "$(dirname "$ENV_FILE")"

TOTAL_STAGES=9

# What #95's last criterion asks for: everything done outside its own steps.
HAND_DONE=()
# Checks that did not pass. The wizard never aborts on one — the operator
# sees it, decides, and it lands in the closing record.
FAILED=()

# remote CMD runs one shell command on the Target. Values are pasted into
# CMD with printf %q by the caller, never bare.
remote() { ssh -o BatchMode=yes "$TARGET_HOST" -- "$1"; }

# q VALUE quotes a value for pasting into a remote command.
q() { printf '%q' "$1"; }

# check "label" CMD runs CMD on the Target and reports ✓ or ✗.
check() {
  local label="$1" cmd="$2"
  if remote "$cmd" > /dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$label"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$label"
    FAILED+=("$label")
    return 1
  fi
}

# show "label" CMD prints what the Target answers, indented, for reading.
show() {
  printf '  %s%s%s\n' "$DIM" "$1" "$RESET"
  remote "$2" 2> /dev/null | sed 's/^/      /' || true
}

# run_cli launches this package's own CLI against the Target profile, in the
# foreground: the operator drives its menu and picks Quit to come back here.
run_cli() {
  say ""
  pause "Press Enter to launch the sandcastle-vps CLI (pick Quit when done)."
  npx @dworznik/sandcastle-vps --target "$TARGET_NAME" || warn "the CLI exited $? — read its output above"
}

# env_on_target KEY prints KEY's value from the Target's .env, or nothing.
env_on_target() {
  remote "sed -n 's/^$1=//p' $(q "$INSTALL_DIR")/.env 2> /dev/null | tail -1"
}

# ok_done "what" reports an action the wizard just took on the Target.
ok_done() { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }

banner "Cut the VPS over from claude-tmux"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "Where things are"
say "Run this from your dev machine. Stage 7 deletes claude-tmux's containers,"
say "so a terminal inside one of them would die halfway."
if [[ -d /opt/claude-tmux || "${HOSTNAME:-}" == claude-tmux* ]]; then
  warn "This looks like the inside of a claude-tmux container. Run it from the dev machine."
  exit 1
fi
say ""
ask TARGET_HOST "ssh destination of the VPS (as in the Target profile, user@host):"
ask TARGET_NAME "Name of the Target profile for it (npx … --target <name>):"
ask INSTALL_DIR "Install directory on the VPS (absolute, usually /home/<user>/.sandcastle-vps):"
ask MEMORY_STORE "Existing claude-mem store on the VPS (the directory claude-tmux mounted at ~/.claude-mem):"
ask CLAUDE_TMUX_DIR "claude-tmux's install directory on the VPS (what it mounted at /opt/claude-tmux):"
ask GPG_KEY_ID "Your own GPG key id, to confirm it is gone from the VPS (Enter to skip):"
write_env TARGET_HOST "$TARGET_HOST"
write_env TARGET_NAME "$TARGET_NAME"
write_env INSTALL_DIR "$INSTALL_DIR"
write_env MEMORY_STORE "$MEMORY_STORE"
write_env CLAUDE_TMUX_DIR "$CLAUDE_TMUX_DIR"
write_env GPG_KEY_ID "$GPG_KEY_ID"
say ""
check "the VPS answers over ssh without a prompt" "true" || {
  warn "fix the ssh connection first"
  exit 1
}
check "docker is on the VPS" "command -v docker"
check "the existing store is there: $MEMORY_STORE" "test -d $(q "$MEMORY_STORE")"
check "claude-tmux is where you said: $CLAUDE_TMUX_DIR" "test -d $(q "$CLAUDE_TMUX_DIR")"
show "claude-tmux containers now:" "docker ps -a --filter name=^claude-tmux --format '{{.Names}}  {{.Status}}'"
pause

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "Upgrade the VPS to a release carrying every slice under #72"
say "The CLI's Install / upgrade delivers this package, rebuilds the Harness,"
say "creates the platform network and moves the stack onto it. Re-running is"
say "safe: every value already in the Target's .env is kept."
step "Pick  Install / upgrade  and let its checks finish; then  Quit."
run_cli
say ""
check "the platform network sandcastle-vps exists" "docker network inspect sandcastle-vps"
check "the stack is on it" "docker network inspect sandcastle-vps -f '{{range .Containers}}{{.Name}} {{end}}' | grep -q harness"
show "version on the VPS:" "sed -n 's/.*\"version\"[[:space:]]*:[[:space:]]*\"\\([^\"]*\\)\".*/\\1/p' $(q "$INSTALL_DIR")/package.json | head -1"
pause

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "Enable sessions, keeping the existing Memory store"
say "MEMORY_DATA_DIR in the Target's .env names a directory the Memory worker"
say "uses as is; empty would mean a fresh named volume. It is set here, before"
say "the toggle, so the service comes up on the current observations."
say ""
if confirm "Write MEMORY_DATA_DIR=$MEMORY_STORE into $INSTALL_DIR/.env on the VPS?"; then
  remote "f=$(q "$INSTALL_DIR")/.env; v=$(q "$MEMORY_STORE"); if grep -q '^MEMORY_DATA_DIR=' \"\$f\"; then sed -i \"s|^MEMORY_DATA_DIR=.*|MEMORY_DATA_DIR=\$v|\" \"\$f\"; else printf 'MEMORY_DATA_DIR=%s\\n' \"\$v\" >> \"\$f\"; fi"
  ok_done "wrote MEMORY_DATA_DIR on the VPS"
else
  HAND_DONE+=("MEMORY_DATA_DIR was not written by the wizard; set it by hand in $INSTALL_DIR/.env before enabling sessions")
fi
say ""
step "Pick  Sessions and access , then  sessions: off — enable it ."
step "Read the trust rule it prints and confirm. Then  Quit."
run_cli
say ""
check "SESSIONS_ENABLED=true on the VPS" "grep -qx 'SESSIONS_ENABLED=true' $(q "$INSTALL_DIR")/.env"
check "the login volume sandcastle-vps-claude exists" "docker volume inspect sandcastle-vps-claude"
check "the Memory service is up" "docker ps --filter label=com.docker.compose.project=sandcastle-vps-memory --format '{{.Status}}' | grep -q '^Up'"
check "the Memory container mounts the existing store" "docker inspect \$(docker ps -q --filter label=com.docker.compose.project=sandcastle-vps-memory) -f '{{range .Mounts}}{{.Source}}{{\"\\n\"}}{{end}}' | grep -qx $(q "$MEMORY_STORE")"
note "The worker waits, saying so in its log, until the plugin is installed in the next stage."
pause

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "Log in once and install the plugins, from inside a Session"
say "The shared ~/.claude volume is empty on a fresh Target: the platform seeds"
say "nothing into it. One login serves every Project's Session from then on."
step "Pick  Sessions , then  Open <project>  for any Onboarded Project."
step "Inside the Session, run the README's first-time checklist:"
say ""
say "      claude auth login"
say "      claude plugin install claude-mem@thedotmack"
say "      claude plugin install <the other plugins you use>"
say ""
step "Detach with  C-b d  (the Session keeps running), then  Quit  the CLI."
run_cli
say ""
check "a Claude login is in the shared volume" "docker run --rm -v sandcastle-vps-claude:/c:ro alpine test -f /c/.credentials.json"
check "the claude-mem plugin is installed in it" "docker run --rm -v sandcastle-vps-claude:/c:ro alpine grep -q claude-mem /c/plugins/installed_plugins.json"
say "  restarting the Memory service so it picks the plugin up…"
remote "cd $(q "$INSTALL_DIR")/memory && docker compose restart > /dev/null 2>&1" || warn "could not restart the Memory service; restart it from $INSTALL_DIR/memory"
sleep 5
show "the worker's health, over the platform network:" "cd $(q "$INSTALL_DIR") && docker run --rm --network sandcastle-vps \"\$(docker compose images -q harness | head -1)\" curl -sS -m 5 http://memory:37777/api/health"
pause

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "Enable access and add each device as a Peer"
say "claude-tmux's WireGuard publishes udp/51820, the port the new service"
say "takes by default, so the old container has to stop first — stopped, not"
say "deleted; stage 7 deletes. This is the one departure from #95's order."
say ""
if remote "docker ps -q --filter name=^claude-tmux-wireguard\$ | grep -q ." 2> /dev/null; then
  if confirm "Stop claude-tmux-wireguard now? Your devices lose the old VPN until the new Peers are added."; then
    remote "docker stop claude-tmux-wireguard > /dev/null"
    ok_done "stopped claude-tmux-wireguard"
    HAND_DONE+=("claude-tmux-wireguard was stopped before enabling access: both publish udp/51820, which #95's order does not account for")
  else
    warn "Enabling access will fail on the port. Pin ACCESS_PORT in the Target's .env, or stop the old container."
    HAND_DONE+=("claude-tmux-wireguard was left running; access needs ACCESS_PORT pinned or the old container stopped")
  fi
fi
say ""
step "Pick  Sessions and access , then  access: off — enable it ."
step "Give the address your devices reach the VPS at (its public hostname or IP)."
step "Then pick  Access , then  Add a Peer  once per device: a name, then a QR"
step "code for a phone or a config file for a laptop. Peer configs from"
step "claude-tmux are not migrated. Then  Quit."
run_cli
say ""
check "ACCESS_ENABLED=true on the VPS" "grep -qx 'ACCESS_ENABLED=true' $(q "$INSTALL_DIR")/.env"
check "the Access service is up" "docker ps --filter label=com.docker.compose.project=sandcastle-vps-access --format '{{.Status}}' | grep -q '^Up'"
check "at least one Peer is recorded" "grep -q '^\\[Peer\\]' $(q "$INSTALL_DIR")/access/peers.conf"
show "Peers recorded:" "grep -c '^\\[Peer\\]' $(q "$INSTALL_DIR")/access/peers.conf"
say ""
step "On one device, connect the new tunnel and open  http://10.13.13.1:8288  — the Orchestrator dashboard."
if ! confirm "Did the dashboard load over the new Access?"; then
  FAILED+=("the Orchestrator dashboard did not load from a Peer over the new Access")
fi

# ── 6 ──────────────────────────────────────────────────────────────────────
stage "Point the DNS layer at the new service"
say "claude-tmux's ddclient keeps the public record at the VPS address too;"
say "two updaters on one record is one too many, so it stops first."
if remote "docker ps -q --filter name=^claude-tmux-ddns\$ | grep -q ." 2> /dev/null; then
  if confirm "Stop claude-tmux-ddns now?"; then
    remote "docker stop claude-tmux-ddns > /dev/null"
    ok_done "stopped claude-tmux-ddns"
    HAND_DONE+=("claude-tmux-ddns was stopped before setting up DNS, so only one updater writes the public record")
  fi
fi
say ""
step "Pick  Access , then  Set up DNS — names for the Target and its services, on Cloudflare ."
step "Give the existing zone, keep or change the public and internal names, and"
step "paste a Cloudflare API token with Zone:Read and DNS:Edit on that zone."
step "It writes both records and starts ddclient. Then  Quit."
run_cli
say ""
check "the zone is recorded" "grep -q '^ACCESS_DNS_ZONE=.' $(q "$INSTALL_DIR")/.env"
check "the token is recorded (its value is never printed)" "grep -q '^CLOUDFLARE_API_TOKEN=.' $(q "$INSTALL_DIR")/.env"
PUBLIC_NAME=$(env_on_target ACCESS_PUBLIC_NAME || true)
INTERNAL_NAME=$(env_on_target ACCESS_INTERNAL_NAME || true)
say "  public name:   ${PUBLIC_NAME:-(none)}"
say "  internal name: ${INTERNAL_NAME:-(none)}"
if [[ -n "$PUBLIC_NAME" ]] && command -v getent > /dev/null 2>&1; then
  if getent hosts "$PUBLIC_NAME" > /dev/null 2>&1; then
    ok_done "$PUBLIC_NAME resolves from here"
  else
    warn "$PUBLIC_NAME does not resolve from here yet — DNS may still be propagating"
  fi
fi
step "From a connected device, open the dashboard by name:  http://${INTERNAL_NAME:-<internal name>}:8288"
if ! confirm "Did it load by the internal name?"; then
  FAILED+=("the dashboard did not load by the internal name from a Peer")
fi

# ── 7 ──────────────────────────────────────────────────────────────────────
stage "Retire claude-tmux: containers, images, volumes, networks"
warn "Irreversible. The zsh history goes with the volumes, by decision; GSD is not reinstalled."
say "The Memory store is NOT touched: it is the directory the new service now uses."
say ""
show "containers:" "docker ps -a --filter name=^claude-tmux --format '{{.Names}}  ({{.Status}})'"
show "images:" "docker images --format '{{.Repository}}:{{.Tag}}' | grep '^claude-tmux'"
show "volumes:" "docker volume ls -q | grep '^claude-tmux'"
show "networks:" "docker network ls --format '{{.Name}}' | grep '^claude-tmux'"
say ""
if confirm "Delete everything listed above?"; then
  remote "docker ps -aq --filter name=^claude-tmux | xargs -r docker rm -f > /dev/null"
  remote "docker images --format '{{.Repository}}:{{.Tag}}' | grep '^claude-tmux' | xargs -r docker rmi -f > /dev/null"
  remote "docker volume ls -q | grep '^claude-tmux' | xargs -r docker volume rm > /dev/null"
  remote "docker network ls --format '{{.Name}}' | grep '^claude-tmux' | xargs -r docker network rm > /dev/null"
  ok_done "removed"
else
  HAND_DONE+=("claude-tmux's containers, images, volumes and networks were NOT deleted by the wizard")
fi
say ""
check "no claude-tmux container remains" "! docker ps -a --format '{{.Names}}' | grep -q '^claude-tmux'"
check "no claude-tmux volume remains" "! docker volume ls -q | grep -q '^claude-tmux'"
check "no claude-tmux image remains" "! docker images --format '{{.Repository}}' | grep -q '^claude-tmux'"
check "no process references $CLAUDE_TMUX_DIR" "! ps -eo args | grep -F $(q "$CLAUDE_TMUX_DIR") | grep -v grep | grep -q ."
note "The directory $CLAUDE_TMUX_DIR itself is left for you to remove once nothing in it is wanted."
HAND_DONE+=("$CLAUDE_TMUX_DIR was left in place, to remove by hand when nothing in it is wanted")
pause

# ── 8 ──────────────────────────────────────────────────────────────────────
stage "Confirm your own signing key is gone, and read status"
say "Your GPG key lived only inside the old container. With it gone, the VPS"
say "should hold no secret key of yours — the agent signs with its own ssh key."
if [[ -n "$GPG_KEY_ID" ]]; then
  check "no secret key $GPG_KEY_ID on the VPS host" "! command -v gpg > /dev/null || ! gpg --list-secret-keys --with-colons $(q "$GPG_KEY_ID") 2> /dev/null | grep -q '^sec'"
else
  check "no secret GPG key at all on the VPS host" "! command -v gpg > /dev/null || ! gpg --list-secret-keys --with-colons 2> /dev/null | grep -q '^sec'"
fi
check "no container mounts a .gnupg directory" "! docker ps -a --format '{{.Mounts}}' | grep -q gnupg"
say ""
check "both toggles are on" "grep -qx 'SESSIONS_ENABLED=true' $(q "$INSTALL_DIR")/.env && grep -qx 'ACCESS_ENABLED=true' $(q "$INSTALL_DIR")/.env"
step "Pick  Status . It should read  Workstation Target — sessions on, access on ,"
step "list your Sessions, the Memory service with the plugin's version, every"
step "Peer, and the Memory UI and dashboard by internal name. Then  Quit."
run_cli
if ! confirm "Did status read as a Workstation Target with access on?"; then
  FAILED+=("status did not read as Workstation Target with access on")
fi
step "Make one commit from a Session and check it shows Verified on GitHub."
if ! confirm "Did a commit from a Session verify on GitHub with the agent's key?"; then
  FAILED+=("a commit from a Session did not verify on GitHub")
fi

# ── 9 ──────────────────────────────────────────────────────────────────────
stage "The record for issue #95"
say "#95 asks for anything done by hand outside its steps to be recorded in a"
say "comment, so the README can be corrected. This is that record:"
say ""
RECORD="Cutover run on $(date -u +%Y-%m-%dT%H:%MZ) with scripts/cutover-from-claude-tmux.sh."
if ((${#HAND_DONE[@]})); then
  RECORD+=$'\n\nDone by hand or outside #95\'s steps:'
  for item in "${HAND_DONE[@]}"; do RECORD+=$'\n- '"$item"; done
else
  RECORD+=$'\n\nNothing was needed outside #95\'s steps.'
fi
if ((${#FAILED[@]})); then
  RECORD+=$'\n\nChecks that did not pass:'
  for item in "${FAILED[@]}"; do RECORD+=$'\n- '"$item"; done
else
  RECORD+=$'\n\nEvery check passed.'
fi
printf '%s\n' "$RECORD" | sed 's/^/  /'
say ""
if command -v gh > /dev/null 2>&1 && confirm "Post this as a comment on dworznik/sandcastle-vps#95 now?"; then
  if printf '%s\n' "$RECORD" | gh issue comment 95 --repo dworznik/sandcastle-vps --body-file - > /dev/null; then
    ok_done "posted"
  else
    SKIPPED+=("post the record above as a comment on #95")
  fi
else
  SKIPPED+=("post the record above as a comment on #95")
fi

finish
